In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.linear_model import SGDRegressor

In [2]:
data = pd.read_csv("project2-data2.csv")

In [3]:
data.head(7)

size  #bedroom   price
0  2104         3  399900
1  1600         3  329900
2  2400         3  369000
3  1416         2  232000
4  3000         4  539900
5  1985         4  299900
6  1534         3  314900

In [4]:
X = data.values[:, 0:2]
y = data.values[:, 2]
m = y.shape[0]

In [5]:
X

array([[2104,    3],
       [1600,    3],
       [2400,    3],
       [1416,    2],
       [3000,    4],
       [1985,    4],
       [1534,    3],
       [1427,    3],
       [1380,    3],
       [1494,    3],
       [1940,    4],
       [2000,    3],
       [1890,    3],
       [4478,    5],
       [1268,    3],
       [2300,    4],
       [1320,    2],
       [1236,    3],
       [2609,    4],
       [3031,    4],
       [1767,    3],
       [1888,    2],
       [1604,    3],
       [1962,    4],
       [3890,    3],
       [1100,    3],
       [1458,    3],
       [2526,    3],
       [2200,    3],
       [2637,    3],
       [1839,    2],
       [1000,    1],
       [2040,    4],
       [3137,    3],
       [1811,    4],
       [1437,    3],
       [1239,    3],
       [2132,    4],
       [4215,    4],
       [2162,    4],
       [1664,    2],
       [2238,    3],
       [2567,    4],
       [1200,    3],
       [ 852,    2],
       [1852,    4],
       [1203,    3]], dtype=int64)

In [6]:
y

array([399900, 329900, 369000, 232000, 539900, 299900, 314900, 198999,
       212000, 242500, 239999, 347000, 329999, 699900, 259900, 449900,
       299900, 199900, 499998, 599000, 252900, 255000, 242900, 259900,
       573900, 249900, 464500, 469000, 475000, 299900, 349900, 169900,
       314900, 579900, 285900, 249900, 229900, 345000, 549000, 287000,
       368500, 329900, 314000, 299000, 179900, 299900, 239500],
      dtype=int64)

In [7]:
m

47

In [8]:
def Feature_Normalize(X):
  X_norm = X.copy()
  mean = np.mean(X_norm, axis= 0)
  range_1 = np.max(X_norm, axis= 0) - np.min(X_norm, axis= 0)
  X_norm = (X_norm - mean)/(range_1)  
  return X_norm, mean, range_1

In [9]:
X_norm, mean, range_1 = Feature_Normalize(X)

In [10]:
model = SGDRegressor(loss= "squared_error" ,
                     fit_intercept= True,
                     max_iter= 5000,
                     learning_rate= "constant",
                     eta0= 0.001)
model.fit(X_norm, y)

SGDRegressor(eta0=0.001, learning_rate='constant', max_iter=5000)

In [11]:
x1_norm = (500 - mean[0]) / range_1[0]
x2_norm = (5 - mean[1]) / range_1[1]
model.predict(np.array([[x1_norm, x2_norm]]))

array([132573.53221318])