In [1]:
import numpy as np
import pandas as pd

In [2]:
data2 = pd.read_csv("project3data2.csv")

In [3]:
data2.head()

test1    test2  Quality
0  0.051267  0.69956        1
1 -0.092742  0.68494        1
2 -0.213710  0.69225        1
3 -0.375000  0.50219        1
4 -0.513250  0.46564        1

In [4]:
X = data2.values[:, 0:2]
y = data2.values[:, 2]
m = y.shape[0]

In [5]:
X

array([[ 0.051267 ,  0.69956  ],
       [-0.092742 ,  0.68494  ],
       [-0.21371  ,  0.69225  ],
       [-0.375    ,  0.50219  ],
       [-0.51325  ,  0.46564  ],
       [-0.52477  ,  0.2098   ],
       [-0.39804  ,  0.034357 ],
       [-0.30588  , -0.19225  ],
       [ 0.016705 , -0.40424  ],
       [ 0.13191  , -0.51389  ],
       [ 0.38537  , -0.56506  ],
       [ 0.52938  , -0.5212   ],
       [ 0.63882  , -0.24342  ],
       [ 0.73675  , -0.18494  ],
       [ 0.54666  ,  0.48757  ],
       [ 0.322    ,  0.5826   ],
       [ 0.16647  ,  0.53874  ],
       [-0.046659 ,  0.81652  ],
       [-0.17339  ,  0.69956  ],
       [-0.47869  ,  0.63377  ],
       [-0.60541  ,  0.59722  ],
       [-0.62846  ,  0.33406  ],
       [-0.59389  ,  0.005117 ],
       [-0.42108  , -0.27266  ],
       [-0.11578  , -0.39693  ],
       [ 0.20104  , -0.60161  ],
       [ 0.46601  , -0.53582  ],
       [ 0.67339  , -0.53582  ],
       [-0.13882  ,  0.54605  ],
       [-0.29435  ,  0.77997  ],
       [-0

In [6]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
m

118

In [8]:
def mapFeature(X, degree= 6):
    X_1 = X[:,0]
    X_2 = X[:,1]
    if X_1.ndim > 0:
        out = [np.ones(X_1.shape[0])]
    else:
        out = [np.ones(1)]

    for i in range(1, degree + 1):
        for j in range(i + 1):
            out.append((X_1 ** (i - j)) * (X_2 ** j))

    if X_1.ndim > 0:
        return np.stack(out, axis= 1)
    else:
        return np.array(out)

In [9]:
X = mapFeature(X, 6)
print(X.shape)

(118, 28)


In [10]:
print("shape of X:", X.shape)
print("shape of y:", y.shape)

shape of X: (118, 28)
shape of y: (118,)


In [11]:
from sklearn import linear_model

In [12]:
model = linear_model.LogisticRegression()
model.fit(X, y)

LogisticRegression()

In [13]:
test_1 = 0.25
test_2 = 0.25
model.predict(mapFeature(np.array([test_1, test_2], ndmin= 2)))

array([1.])